#!/bin/bash
FROM alpine:latest
MAINTAINER Olga Struska <olga.struska@edu.pollub.pl>

RUN apk --no-cache --update upgrade 

RUN apk add openrc 

RUN apk add apache2 php$phpverx-apache2

COPY Zadanie1.php /var/www/localhost/htdocs/index.php
RUN rm -rf /var/www/localhost/htdocs/index.html

EXPOSE 81
CMD ["-D", "FOREGROUND"]


ENTRYPOINT ["/usr/sbin/httpd"]
